export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY'
export const GET_POST_FROM_CATEGORY = 'GET_POST_FROM_CATEGORY'
export const GET_ALL_POST = 'GET_ALL_POST'
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'
export const CREATE_POST = "CREATE_POST" 
export const UPDATE_POST = "UPDATE_POST"
export const DELETE_POST = "DELETE_POST"